---
- name: Run command on all running VMs using OCI Instance Agent
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: "us-ashburn-1"
    compartment_ocid: "ocid1.compartment.oc1..aaaaaaaaswfncccqcgnx77btfb42d2fzclr54ewepxnfvquwzvvhtf6vibea"

  tasks:

    - name: Get running instances
      oracle.oci.oci_compute_instance_facts:
        compartment_id: "{{ compartment_ocid }}"
        region: "{{ region }}"
      register: instance_list

    - name: Filter RUNNING instances
      set_fact:
        running_instances: >
          {{ instance_list.instances
             | selectattr('lifecycle_state','equalto','RUNNING')
             | list }}

    - name: Run command via Instance Agent
      oracle.oci.oci_compute_instance_agent_instance_agent_command:
        compartment_id: "{{ compartment_ocid }}"
        region: "{{ region }}"
        display_name: "ansible-run-command"
        target:
          instance_ids:
            - "{{ item.id }}"
        content:
          content_type: "TEXT"
          content: |
            #!/bin/bash
            echo "Running on $(hostname)"
            uptime
      loop: "{{ running_instances }}"
      register: run_result

    - name: Show results
      debug:
        var: run_result
