---
- name: Run command on ALL VMs in compartment
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - oracle.oci

  vars:
    config_file: "~/.oci/config"
    profile: "DEFAULT"
    region: "us-ashburn-1"
    compartment_ocid: "ocid1.compartment.oc1..xxxx"

  tasks:

    - name: Get instances
      oci_compute_instance_facts:
        config_file_location: "{{ config_file }}"
        config_profile_name: "{{ profile }}"
        region: "{{ region }}"
        compartment_id: "{{ compartment_ocid }}"
      register: instance_list

    - name: Filter RUNNING instances
      set_fact:
        running_instances: >
          {{ instance_list.instances
             | selectattr('lifecycle_state','equalto','RUNNING')
             | list }}

    - name: Run command using OCI Run Command
      oci_compute_instance_action:
        config_file_location: "{{ config_file }}"
        config_profile_name: "{{ profile }}"
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
        action: RUN_COMMAND
        run_command_details:
          command: |
            #!/bin/bash
            hostname
            date
      loop: "{{ running_instances }}"
