---
- name: Execute OCI Run Command
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Run command on each running VM
      oracle.oci.oci_compute_instance_run_command:
        # Required: The OCID of the instance
        instance_id: "ocid1.compartment.oc1..aaaaaaaaswfncccqcgnx77btfb42d2fzclr54ewepxnfvquwzvvhtf6vibea"
        # The actual command to run
        command: "uptime"
        # Optional: Specify the interpreter
        # interpreter: "/bin/bash"
      register: result

    - name: Debug the output
      debug:
        var: result
